apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongo-ns
spec:
  replicas: 3
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
      namespace: mongo-ns
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          workingDir: /home/mongodb
          volumeMounts:
            - name: mongo-key
              mountPath: /tmp/mongoKey
            - name: mongo-script
              mountPath: /home/mongodb/scripts
            - name: mongo-setup
              mountPath: /docker-entrypoint-initdb.d
            - name: mongo-data
              mountPath: /data/db
          ports:
            - containerPort: 27017
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_REPLICAS
              value: "3"
          envFrom:
            - configMapRef:
                name: mongo-env
            - secretRef:
                name: mongo-secret
          command:
            - /bin/sh
            - -c
          args:
            - |
              /home/mongodb/scripts/change-key-permission.sh && \
              docker-entrypoint.sh mongod \
                --replSet rs0 \
                --bind_ip_all \
                --keyFile /home/mongodb/mongoKey/keyFile
      volumes:
        - name: mongo-key
          configMap:
            name: mongo-key
        - name: mongo-setup
          configMap:
            name: mongo-setup
        - name: mongo-script
          configMap:
            name: mongo-script
            defaultMode: 0755
        - name: mongo-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume-claim
      spec:
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce
