apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-script
  namespace: mongo-ns
data:
  prepare.sh: |
    cp /home/mongodb/security/* /home/mongodb/
    
    chmod 400 /home/mongodb/root-ca.crt
    chmod 400 /home/mongodb/admin.pem
    chown -R mongodb:mongodb /home/mongodb/root-ca.crt
    chown -R mongodb:mongodb /home/mongodb/admin.pem

    cd /home/mongodb/

    openssl req -sha256 -new -nodes \
      -subj "/CN=${K8S_POD_NAME}.mongo/O=WW" \
      -out node.csr \
      -keyout node.key
    
    openssl x509 -req -sha256 -days 365 \
      -in node.csr \
      -CA root-ca.crt \
      -CAkey root-ca.key \
      -CAcreateserial \
      -out node.crt \
      -passin pass:2012

    cat node.crt node.key > node.pem
